name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Algorithms
      run: go build -v github.com/hambrosia/algorithms-golang...

    - name: Test Algorithms
      run: go test -v github.com/hambrosia/algorithms-golang...
